#!/bin/sh

# The following comment lines are used by the init setup script like the
# chkconfig command for RedHat based distributions. Change as
# appropriate for your installation.

### BEGIN INIT INFO
# Provides:          nexus-iq-server
# Required-Start:    $local_fs $remote_fs $network $time $named
# Required-Stop:     $local_fs $remote_fs $network $time $named
# Default-Start:     2 3 5
# Default-Stop:      0 1 2 6
# Short-Description: nexus-iq-server service
# Description:       Start the nexus-iq-server service
### END INIT INFO

NEXUS_IQ_SERVER_HOME=/opt/sonatype/iqserver
VERSION=replaceMeIQServerVersion
JAVA_OPTIONS="-Xmx4096m -XX:+UseG1GC"

do_start()
{
    cd $NEXUS_IQ_SERVER_HOME
    java $JAVA_OPTIONS -jar nexus-iq-server-$VERSION.jar server config.yml
    echo "Started nexus-iq-server"
}

do_console()
{
    cd $NEXUS_IQ_SERVER_HOME
    java $JAVA_OPTIONS -jar nexus-iq-server-$VERSION.jar server config.yml
}

do_stop()
{
    # NOTE: Be sure the command to find pid will not kill the installer process by mistake (rpm|deb|dpkg)
    pid=`ps aux | grep nexus-iq-server | grep '.jar server' | grep -vE '(stop|grep|rpm|deb|dpkq)' | awk '{print $2}'`
    kill $pid
    echo "Killed nexus-iq-server - PID $pid"
}

do_usage()
{
    echo "Usage: nexus-iq-server [console|start|stop]"
}

case $1 in
    console)
        do_console
        ;;
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    *)
        do_usage
        ;;
esac
