#
# Copyright 2022-Present Sonatype Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For details of what checks are run for PRs please refer below
# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Installer
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Build RPM and DEB
        run: |
          make docker-all
          export RPM_NAME=`make show-rpm-name`
          export DEB_NAME=`make show-deb-name`
          echo RPM_NAME: $RPM_NAME
          echo DEB_NAME: $DEB_NAME
          # store names in env vars for later steps to use
          #echo export RPM_NAME="${RPM_NAME}" >> "$BASH_ENV"
          echo "RPM_NAME=$(echo $RPM_NAME)" >> $GITHUB_ENV
          #echo export DEB_NAME="${DEB_NAME}" >> "$BASH_ENV"
          echo "DEB_NAME=$(echo $DEB_NAME)" >> $GITHUB_ENV
      - name: Upload installer RPM
        uses: actions/upload-artifact@v3
        with:
          name: rpmFile
          path: build/${{ env.RPM_NAME }}
      - name: Upload installer DEB
        uses: actions/upload-artifact@v3
        with:
          name: debFile
          path: build/${{ env.DEB_NAME }}

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
